import type { Experience } from './types';

export const experiences: Experience[] = [
  {
    id: 'pignus-vr',
    company: 'Pignus',
    role: 'Frontend Developer & Unity VR Developer',
    period: '2023 - Present',
    description: 'Modernized reporting dashboard and developed VR applications for Meta Quest',
    achievements: [
      'Migrated legacy PHP Laravel dashboard to modern Vue + Inertia.js stack',
      'Implemented Vite build system and Pinia state management',
      'Created interactive data visualizations and charts',
      'Developed Unity VR applications for Meta Quest',
      'Implemented interactive VR mechanics and experiences',
      'Optimized performance for standalone VR hardware',
      'Integrated Quest SDK features and controllers',
    ],
    technologies: ['Vue', 'Inertia.js', 'Vite', 'Pinia', 'PHP', 'Unity', 'C#', 'Meta Quest SDK'],
    category: 'fullstack',
  },
  {
    id: 'ucl-neurospeech',
    company: 'UCL',
    role: 'Frontend Developer - NeurospeechAI',
    period: 'Mar 2023 – Jun 2023',
    description: 'Leading frontend development for an accessible neuroscience research platform',
    achievements: [
      'Built complete frontend using React, TypeScript, and Vite',
      'Designed and implemented comprehensive design system from scratch',
      'Created accessible, reusable component library',
    ],
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
    category: 'frontend',
  },
  {
    id: 'capitalizarme',
    company: 'Capitalizarme',
    role: 'Frontend Developer',
    period: 'May 2022 – Mar 2023',
    description: 'Built performant financial platform with React and Next.js',
    achievements: [
      'Developed responsive frontend using React, TypeScript, and Next.js',
      'Implemented Redux for complex state management',
      'Optimized performance and bundle size',
      'Ensured cross-browser compatibility and responsive design',
    ],
    technologies: ['React', 'TypeScript', 'Next.js', 'Redux', 'CSS'],
    category: 'frontend',
  },
  {
    id: 'eye-search',
    company: 'UCL',
    role: 'Full-Stack Developer - Eye-Search',
    period: 'Jan 2022 – Apr 2022',
    description: 'Built research platform integrating React frontend with Unity WebGL',
    achievements: [
      'Developed React + TypeScript frontend for research application',
      'Integrated Unity WebGL experiments into web platform',
      'Designed site architecture, authentication, and navigation',
      'Created seamless communication between web and Unity layers',
    ],
    technologies: ['React', 'TypeScript', 'Unity', 'WebGL', 'Authentication'],
    category: 'fullstack',
  },
   {
    id: 'title',
    company: 'University of Chile',
    role: 'Unity Developer & UI/UX Designer',
    period: 'Feb 2020 – Jun 2021',
    description: 'Designed and developed VR-based user experience studies with Unity and Blender, focusing on ergonomic and intuitive interaction models for cognitive research.',
    achievements: [
      'Applied UX design principles from web development to immersive 3D environments using C# and Oculus Quest integration.',
    ],
    technologies: ['React', 'TypeScript', 'Unity', 'WebGL', 'Authentication'],
    category: 'fullstack',
  },
  {
    id: 'pulso-escolar',
    company: 'Pulso Escolar',
    role: 'Frontend Developer',
    period: 'Jan 2019 – Dec 2019',
    description: 'Developed educational dashboards with Vue.js',
    achievements: [
      'Built interactive Vue.js dashboards for educational data',
      'Implemented data visualization components',
      'Deployed and maintained on Google Cloud Platform',
      'Created responsive and intuitive interfaces',
    ],
    technologies: ['Vue', 'JavaScript', 'Google Cloud Platform', 'Data Visualization'],
    category: 'frontend',
  },
  {
    id: 'nlhpc',
    company: 'NLHPC (National Laboratory for High Performance Computing)',
    role: 'Frontend Developer Intern',
    period: 'Jul 2018 – Dec 2018',
    description: 'Created monitoring dashboards for HPC infrastructure',
    achievements: [
      'Developed React dashboards for monitoring HPC systems',
      'Implemented GraphQL queries and subscriptions',
      'Visualized real-time system metrics and performance data',
      'Collaborated with backend team on API design',
    ],
    technologies: ['React', 'GraphQL', 'JavaScript', 'Data Visualization'],
    category: 'frontend',
  },
];
