import type { Project } from './types';

export const projects: Project[] = [
  {
    id: 'neurospeech-platform',
    title: 'NeurospeechAI Research Platform',
    company: 'UCL',
    problem: 'Neuroscience researchers needed an accessible web platform to conduct speech processing experiments, but existing tools lacked proper accessibility and modern UX.',
    contribution: 'Built the frontend from scratch using React, TypeScript, and Vite.',
    outcome: 'Delivered a production-ready platform currently being used by researchers to conduct studies with diverse participant groups. The design system provides a foundation for consistent, accessible component development.',
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
    category: 'web',
    image: '/SimpleProtafolio/projects/neurospeech.png',
    link: 'https://neurospeechai.com/',
  },
  {
    id: 'pignus-dashboard',
    title: 'Modern Reporting Dashboard',
    company: 'Pignus',
    problem: 'Legacy PHP Laravel dashboard was slow, hard to maintain, and lacked interactivity for data visualization.',
    contribution: 'Migrated frontend to Vue 3 + Inertia.js with Vite build system. Implemented Pinia for state management and created interactive charts. Maintained backend API compatibility while modernizing the frontend architecture.',
    outcome: 'Significantly improved page load performance and developer experience. The modern stack enabled faster feature development and more responsive data visualizations.',
    technologies: ['Vue 3', 'Inertia.js', 'Vite', 'Pinia', 'PHP Laravel', 'Chart.js'],
    category: 'web',
    image: '/SimpleProtafolio/projects/pignus-plataform.png',
    link: 'https://www.pignus.cl/plataforma/',
  },
  {
    id: 'quest-vr-experiences',
    title: 'Meta Quest VR Applications',
    company: 'Pignus',
    problem: 'Client needed immersive VR experiences for training and evaluation, optimized for standalone Quest hardware.',
    contribution: 'Developed Unity VR applications using Meta Quest SDK. Implemented intuitive hand tracking and controller interactions. Optimized rendering and assets for Quest 2 performance constraints.',
    outcome: 'Delivered VR applications that run smoothly on Quest 2 and Quest 3 hardware. Applications are currently in use for evaluation and training purposes.',
    technologies: ['Unity', 'C#', 'Meta Quest SDK', 'VR Optimization'],
    category: 'vr',
    image: '/SimpleProtafolio/projects/pignus-vr.png',
  },
  {
    id: 'eye-search-webgl',
    title: 'Eye-Search Research Platform',
    company: 'UCL',
    problem: 'Researchers needed to deploy Unity-based eye-tracking experiments on the web, accessible to participants remotely.',
    contribution: 'Built React + TypeScript frontend and integrated Unity WebGL builds. Created seamless authentication flow and data synchronization between web and Unity contexts. Designed architecture for deploying and versioning experiments.',
    outcome: 'Platform successfully enabled remote participation in eye-tracking research, particularly valuable during pandemic restrictions. Continues to support ongoing research studies.',
    technologies: ['React', 'TypeScript', 'Unity', 'WebGL', 'Authentication'],
    category: 'web',
    link: 'https://eye-search.co.uk/',
    image: '/SimpleProtafolio/projects/eyesearch.png',
  },
  {
    id: 'capitalizarme-platform',
    title: 'Financial Services Platform',
    company: 'Capitalizarme',
    problem: 'Financial platform required robust state management and high performance for handling sensitive transactions.',
    contribution: 'Developed features using React, TypeScript, and Next.js as part of the frontend team. Implemented Redux-based state management for complex financial flows. Contributed to performance optimizations including bundle size reduction and code splitting.',
    outcome: 'Contributed to a high-performance platform handling significant daily transaction volume with fast load times and excellent performance metrics.',
    technologies: ['React', 'TypeScript', 'Next.js', 'Redux'],
    category: 'web',
    image: '/SimpleProtafolio/projects/capitalizarme.png',
  },
  {
    id: 'pulso-escolar-dashboards',
    title: 'Educational Analytics Dashboards',
    company: 'Pulso Escolar',
    problem: 'Educational institutions needed intuitive dashboards to visualize student performance and attendance data.',
    contribution: 'Built responsive Vue.js dashboards with interactive charts for educational data visualization. Created reusable component library for consistent data presentation across modules. Set up automated CI/CD deployment pipelines on Google Cloud Platform.',
    outcome: 'Deployed to multiple schools across Chile, helping educators access and understand student data more effectively.',
    technologies: ['Vue', 'Google Cloud Platform', 'Data Visualization'],
    category: 'web',
    image: '/SimpleProtafolio/projects/radar.png',
  },
];
